services:
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - db_data:/data/db

  redis:
    image: redis:latest
    container_name: secure_redis
    restart: unless-stopped
    command: ['redis-server', '/usr/local/etc/redis/redis.conf']
    ports:
      - '6379:6379'
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD_DOCKER}
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    networks:
      - redis_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: skyvc_nest_docker
    environment:
      - MONGO_URI=${MONGO_URI_DOCKER}
    env_file:
      - .env
    ports:
      - '4008:3009'
    depends_on:
      - mongodb
    volumes:
      - ./src:/app/src
    networks:
      - redis_network

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo_express
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_SERVER: 172.19.0.2
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_URL: ${MONGO_URI_DOCKER}
    depends_on:
      - mongodb
    networks:
      - redis_network
    command: sh -c "until nc -z 172.19.0.2 27017; do sleep 1; done; mongo-express"

volumes:
  db_data:
  redis_data:

networks:
  redis_network:
    driver: bridge
